openapi: 3.0.1
info:
  title: Movie API
  description: API for managing movie objects.
  version: 1.0.0
paths:
  /movies:
    post:
      summary: Create a new movie
      description: Publishes a movie object with the name and reviews fields.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Movie'
      responses:
        '201':
          description: Movie created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieResponse'
        '400':
          description: Bad request
        '500':
          description: Server error

    get:
      summary: List all movies
      description: Retrieve a list of all movie objects.
      responses:
        '200':
          description: A list of movies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovieResponse'

  /movies/{id}:
    get:
      summary: Retrieve a single movie
      description: Retrieve a single movie object by its ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier for the movie
          schema:
            type: string
      responses:
        '200':
          description: A single movie object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieResponse'
        '404':
          description: Movie not found
        '500':
          description: Server error

components:
  schemas:
    Review:
      type: object
      properties:
        review:
          type: string
          description: The review text
          example: "Great movie with a compelling story."
        hintNumber:
          type: integer
          description: A hint number from 1 to 5
          example: 4
          minimum: 1
          maximum: 5
      required:
        - review
        - hintNumber

    Movie:
      type: object
      properties:
        name:
          type: string
          description: The name of the movie
          example: "Inception"
        dailyDate:
          type: string
          format: date
        reviews:
          type: array
          items:
            $ref: '#/components/schemas/Review'
          description: A list of reviews for the movie
          example:
            - review: "Great movie with a compelling story."
              hintNumber: 5
            - review: "Amazing visuals and soundtrack."
              hintNumber: 4
      required:
        - name

    MovieResponse:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier for the movie
          example: "60d5f60b24eaa632dcd28b6b"
        name:
          type: string
          description: The name of the movie
          example: "Inception"
        dailyDate:
          type: string
          format: date
        reviews:
          type: array
          items:
            $ref: '#/components/schemas/Review'
          description: A list of reviews for the movie
          example:
            - review: "Great movie with a compelling story."
              hintNumber: 5
            - review: "Amazing visuals and soundtrack."
              hintNumber: 4
      required:
        - id
        - name
        - reviews
